# Generated by Django 5.2 on 2025-04-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_picture',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
